config/routes.rb
Rails.application.routes.draw do
  resources :stocks do
    resources :stock_change_logs, only: [ :index ]
  end
  resources :drugs
  resource :session
  resources :passwords, param: :token
  resources :clerks
  resources :stores do
    resources :visits
  end
  resources :inline_edits, only: [ :update ]
  get "dashboard/index"
  get "dashboard/store/:store_id", to: "dashboard#store", as: "dashboard/store/"
  post "dashboard/store/:store_id", to: "dashboard#store"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @user = Current.user
  end

  def store
    @user = Current.user
    @store = Store.find(params[:store_id])
    @visits = @store.visits.order(created_at: :desc).limit(5)
    @clerk = Clerk.new(store_id: @store.id)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_drug_table_line_item.html.erb
<tr id="stock_<%= stock.id %>">
  <td><%= stock.drug.product_name %></td>

  <td data-controller="inline-edit"
      data-inline-edit-url-value="<%= inline_edit_path(stock) %>">
    <div data-inline-edit-target="display">
      <%= stock.quantity %>
    </div>
    <%= form_with(model: stock,
                  data: { inline_edit_target: "form", action: "submit->inline-edit#submit"},
                  class: "d-none") do |f| %>
      <%= hidden_field_tag :resource_type, "stock" %>
      <%= f.number_field :quantity, class: "form-control",
                  data: { inline_edit_target: "input"} %>
    <% end %>
  </td>

  <td data-controller="inline-edit"
      data-inline-edit-url-value="<%= inline_edit_path(stock) %>">
    <div data-inline-edit-target="display">
      <%= stock.distribution_quantity %>
    </div>
    <%= form_with(model: stock,
                  data: { inline_edit_target: "form", action: "submit->inline-edit#submit"},
                  class: "d-none") do |f| %>
      <%= hidden_field_tag :resource_type, "stock" %>
      <%= f.number_field :distribution_quantity, class: "form-control",
                  data: { inline_edit_target: "input" } %>
    <% end %>
  </td>

  <td>
    <%= link_to stock_stock_change_logs_path(stock), class: "btn btn-sm btn-primary" do %>
      <i class="bi bi-list-check"></i>
      日志
    <% end %>
  </td>
</tr>

app/views/dashboard/_visit_of_store_item.html.erb
<% if index.even? %>
  <div class="card mb-3">
<% else %>
  <div class="card mb-3 bg-light-subtle">
<% end %>
  <div class="card-header"><%= visit.created_at.strftime("%Y-%m-%d %H:%M") %></div>
  <div class="card-body">
    <%= visit.content %>
  </div>
</div>

app/views/dashboard/index.html.erb
<div class="row mt-3">
  <div class="col-12 mb-3">
    <div class="card">
      <div class="card-body row">
        <div class="col-8"><p class="card-title"><%= @user.email_address%> 的工作台</p></div>
        <div class="col-4"><%= button_to "登出系统", session_path(@user), method: :delete, data: { turbo_confirm: "确定登出系统？" }, class: "btn btn-sm btn-danger float-end" %></div>
      </div>
    </div>
  </div>
  <div class="col-6 col-sm-3 mb-3">
    <div class="card">
      <div class="card-body">
        <small class="text-secondary">当前负责终端</small>
        <p class="fs-1 fw-bolder text-center mb-0 "><%= @user.stores.count %></p>
      </div>
    </div>
  </div>
  <div class="col-6 col-sm-3 mb-3">
    <div class="card">
      <div class="card-body">
        <small class="text-secondary">当前负责药品</small>
        <p class="fs-1 fw-bolder text-center mb-0 "><%= @user.drugs.count %></p>
      </div>
    </div>
  </div>
  <div class="col-6 col-sm-3 mb-3">
    <div class="card">
      <div class="card-body">
        <small class="text-secondary">当前负责店员</small>
        <p class="fs-1 fw-bolder text-center mb-0 "><%= @user.clerks.count %></p>
      </div>
    </div>
  </div>
    <div class="col-6 col-sm-3 mb-3">
    <div class="card">
      <div class="card-body">
        <small class="text-secondary">总计拜访</small>
        <p class="fs-1 fw-bolder text-center mb-0 "><%= @user.visits.count %></p>
      </div>
    </div>
  </div>
  <div class="col-12">
    <% @user.stores.each_with_index do |store, index| %>
      <%= render store, index: index %>
    <% end %>
  </div>
</div>

app/views/dashboard/store.html.erb
<div class="col-12 my-3">
  <div class="card">
    <div class="card-body">
      <%= @store.name %>
    </div>
  </div>
</div>

<nav>
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true">终端库存</button>
    <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">店员清单</button>
    <button class="nav-link" id="nav-contact-tab" data-bs-toggle="tab" data-bs-target="#nav-contact" type="button" role="tab" aria-controls="nav-contact" aria-selected="false">拜访记录</button>
  </div>
</nav>

<div class="tab-content" id="nav-tabContent">
  <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab" tabindex="0">
    <div class="col-12 mt-3">
      <table class="table table-striped">
        <thead class="sticky-top bg-white">
          <tr>
            <th>药品名称</th>
            <th>库存</th>
            <th>分销数量</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <% @store.stocks.each do |stock| %>
            <%= render partial: "drug_table_line_item", locals: { stock: stock } %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab" tabindex="0">
    <div class="row mt-3" data-controller="form">
      <div class="col-6 col-sm-3 mb-3">
        <div class="card">
          <div class="card-body">
            <small class="text-secondary">在职店员</small>
            <p class="fs-1 fw-bolder text-center mb-0" id="clerk_count"><%= @store.clerks.active.count %></p>
          </div>
        </div>
      </div>
      <div class="col-6 col-sm-3 mb-3">
        <div class="card">
          <div class="card-body">
            <small class="text-secondary">已离职店员</small>
            <p class="fs-1 fw-bolder text-center mb-0 "><%= @store.clerks.resigned.count %></p>
          </div>
        </div>
      </div>
      <div class="col-6 col-sm-3 mb-3">
        <div class="card">
          <div class="card-body">
            <small class="text-secondary">该终端共有店员</small>
            <p class="fs-1 fw-bolder text-center mb-0 "><%= @store.clerks.count %></p>
          </div>
        </div>
      </div>
      <div class="col-6 col-sm-3 mb-3">
        <div class="card">
          <div class="card-body">
            <small class="text-secondary">本月新增</small>
            <p class="fs-1 fw-bolder text-center mb-0 "><%= @store.clerks.created_this_month.count %></p>
          </div>
        </div>
      </div>
      <div class="col-12 mb-3">
        <button type="button" class="btn btn-primary float-end" data-action="form#toggleForm">
          <i class="bi bi-plus-circle"></i> 新增店员
        </button>
      </div>
      <div id="new_clerk_form" class="col-12" data-form-target="form" style="display: none;">
        <%= render "clerks/form_modal", clerk: @clerk %>
      </div>
      <div id="clerks">
        <% @store.clerks.each_with_index do |clerk, index| %>
          <div class="col-12">
            <%= render clerk, index: index %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab" tabindex="0">
    <div class="col-12 mt-3">
      <%= link_to "新建拜访记录", new_store_visit_path(@store), class: "btn btn-primary" %>
      <%= link_to "管理该店的拜访记录", store_visits_path(@store), class: "btn btn-outline-primary" %>
    </div>
    <div class="col-12 mt-3">
      <% @visits.each_with_index do |visit, index| %>
        <%= render "visit_of_store_item", visit: visit, index: index %>
      <% end %>
    </div>
  </div>
</div>