config/routes.rb
Rails.application.routes.draw do
  resources :stocks do
    resources :stock_change_logs, only: [ :index ]
  end
  resources :drugs
  resource :session
  resources :passwords, param: :token
  resources :clerks
  resources :stores do
    resources :visits
  end
  resources :inline_edits, only: [ :update ]
  get "dashboard/index"
  get "dashboard/store/:store_id", to: "dashboard#store", as: "dashboard/store/"
  post "dashboard/store/:store_id", to: "dashboard#store"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/models/clerk.rb
class Clerk < ApplicationRecord
  before_validation :blank_customer_preference_to_nil

  belongs_to :store

  validates :first_name, :last_name, presence: true

  scope :resigned, -> { where(resigned: true) }
  scope :active, -> { where(resigned: false) }
  scope :created_this_month, -> { where(created_at: Time.current.beginning_of_month..Time.current.end_of_month) }

  # enum customer_preference: {
  #   A: "A",
  #   B: "B",
  #   C: "C"
  # }, _prefix: true

  def fullname
    last_name + first_name
  end

  private

  def blank_customer_preference_to_nil
    self.customer_preference = nil if customer_preference.blank?
  end
end

app/controllers/clerks_controller.rb
class ClerksController < ApplicationController
  before_action :set_clerk, only: %i[ show edit update destroy ]

  # GET /clerks or /clerks.json
  def index
    @clerks = Clerk.all
  end

  # GET /clerks/1 or /clerks/1.json
  def show
  end

  # GET /clerks/new
  def new
    @clerk = Clerk.new
    @clerk.store_id = params[:store_id]
  end

  # GET /clerks/1/edit
  def edit
  end

  # POST /clerks or /clerks.json
  def create
    @clerk = Clerk.new(clerk_params)

    respond_to do |format|
      if @clerk.save
        format.turbo_stream {
          render turbo_stream: [
            turbo_stream.append("clerks", partial: "clerks/clerk", locals: { clerk: @clerk, index: @clerk.store.clerks.count - 1 }),
            turbo_stream.replace("clerk_count", partial: "clerks/count", locals: { count: @clerk.store.clerks.count })
          ]
        }
        format.html { redirect_to store_url(@clerk.store), notice: "Clerk was successfully created." }
        format.json { render :show, status: :created, location: @clerk }
      else
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace(
            "new_clerk_form",
            partial: "clerks/form_modal",
            locals: { clerk: @clerk }
          )
        }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @clerk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clerks/1 or /clerks/1.json
  def update
    respond_to do |format|
      if @clerk.update(clerk_params)
        format.html { redirect_to @clerk, notice: "Clerk was successfully updated." }
        format.json { render :show, status: :ok, location: @clerk }
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace(
            @clerk,
            partial: "clerks/clerk",
            locals: { clerk: @clerk }
          )
        }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @clerk.errors, status: :unprocessable_entity }
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace(
            @clerk,
            partial: "clerks/clerk",
            locals: { clerk: @clerk }
          )
        }
      end
    end
  end

  # DELETE /clerks/1 or /clerks/1.json
  def destroy
    @clerk.destroy!

    respond_to do |format|
      format.html { redirect_to clerks_path, status: :see_other, notice: "Clerk was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clerk
      @clerk = Clerk.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def clerk_params
      params.expect(clerk: [ :first_name, :last_name, :gender, :remark, :store_id, :customer_preference, :resigned ])
    end
end

app/helpers/clerks_helper.rb
module ClerksHelper
end

app/views/clerks/_clerk.html.erb
<div id="<%= dom_id clerk %>" class="card mb-3" data-controller="clerk">
  <div class="card-header">
    <div class="row">
      <div class="col-auto">
        <% if local_assigns.has_key?(:index) %>
          <span class="badge text-secondary-emphasis bg-secondary-subtle"><%= index+1 %></span>
        <% end %>
      </div>
      <div class="col-auto fs-5">
        <%= clerk.fullname %>
      </div>
      <div class="col-auto fs-5">
        <%= clerk.gender %>
      </div>
      <div class="col-auto ms-auto">
        <div class="form-check form-switch">
          <%= form_with(model: clerk, url: inline_edit_path(clerk), method: :patch, data: { turbo: true }) do |form| %>
            <%= hidden_field_tag :resource_type, "clerk" %>
            <%= hidden_field_tag :index, local_assigns[:index] if local_assigns.has_key?(:index) %>
            <%= form.check_box :resigned, 
                class: "form-check-input", 
                data: { 
                  action: "change->clerk#toggleResigned",
                  bs_placement: "left",
                  turbo_confirm: clerk.resigned ? "是否确认该店员已复职？" : "是否确认该店员已离职？"
                } %>
            <%= form.label :resigned, class: "form-check-label" do %>
              <span class="<%= clerk.resigned ? 'text-danger' : 'text-success' %>">
                <%= clerk.resigned ? '已离职' : '在职' %>
              </span>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="card-body">
    <p class="mb-0 fs-5">
      客户倾向性：
      <b><%= clerk.customer_preference ? clerk.customer_preference : "未明" %></b>
      <button class="btn btn-outline-primary ms-4"
              type="button"
              id="edit-btn-<%= clerk.id %>"
              style="display: inline-block;"
              onclick="document.getElementById('customer-preference-edit-<%= clerk.id %>').style.display='block';this.style.display='none'">
        修改
      </button>
      <div id="customer-preference-edit-<%= clerk.id %>" style="display:none;">
        <hr />
        <%= form_with(model: clerk, url: inline_edit_path(clerk), method: :patch, local: true) do |form| %>
          <%= hidden_field_tag :resource_type, "clerk" %>
          <%= form.radio_button :customer_preference, 'A' %>
          <%= form.label :customer_preference_A, 'A', class: "me-4 ms-2 fs-5" %>
          <%= form.radio_button :customer_preference, 'B' %>
          <%= form.label :customer_preference_B, 'B', class: "me-4 ms-2 fs-5" %>
          <%= form.radio_button :customer_preference, 'C' %>
          <%= form.label :customer_preference_C, 'C', class: "me-4 ms-2 fs-5" %>
          <%= form.radio_button :customer_preference, '' %>
          <%= form.label :customer_preference_none, '不明', class: "me-4 ms-2 fs-5" %>
          <%= form.submit "保存", class: "btn btn-success ms-2" %>
          <button type="button" class="btn btn-secondary ms-2"
            onclick="
              document.getElementById('customer-preference-edit-<%= clerk.id %>').style.display='none';
              document.getElementById('edit-btn-<%= clerk.id %>').style.display='inline-block';
            ">
            取消
          </button>
        <% end %>
      </div>
    </p>
    <hr />
    <span class="d-inline-flex px-2 py-1 me-1 mb-1 text-success-emphasis bg-success-subtle border border-success-subtle rounded-2">温和可信</span>
    <span class="d-inline-flex px-2 py-1 me-1 mb-1 text-danger-emphasis bg-danger-subtle border border-danger-subtle rounded-2">技术专业</span>
    <span class="d-inline-flex px-2 py-1 me-1 mb-1 text-info-emphasis bg-info-subtle border border-info-subtle rounded-2">成本敏感</span>
    <span class="d-inline-flex px-2 py-1 me-1 mb-1 text-primary-emphasis bg-primary-subtle border border-primary-subtle rounded-2">口才优秀</span>
  </div>
</div>

app/views/clerks/_count.html.erb
<p class="fs-1 fw-bolder text-center mb-0" id="clerk_count"><%= count %></p> 

app/views/clerks/_form.html.erb
<%= form_with(model: clerk) do |form| %>
  <% if clerk.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show">
      <strong><%= t('errors.template.header', 
                    count: clerk.errors.count, 
                    model: clerk.class.model_name.human) %>
      </strong>

      <ul class="m-0">
        <% clerk.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
      
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>

  <div class= "mb-3">
    <%= form.label :last_name, style: "display: none", class: "form-label" %>
    <%= form.text_field :last_name, class: "form-control", placeholder: "姓氏"  %>
  </div>

  <div class= "mb-3">
    <%= form.label :first_name, style: "display: none", class: "form-label" %>
    <%= form.text_field :first_name, class: "form-control", placeholder: "名字"  %>
  </div>

  <div class= "mb-3">
    <%= form.label :gender, style: "display: none", class: "form-label" %>
    <%= form.text_field :gender, class: "form-control", placeholder: "性别"  %>
  </div>

  <div class= "mb-3">
    <%= form.label :remark, style: "display: none", class: "form-label" %>
    <%= form.textarea :remark, class: "form-control", placeholder: "备注", rows: 5  %>
  </div>

  <div class="mb-3">
    <label class="form-label">客户倾向性</label>
    <div>
      <%= form.radio_button :customer_preference, 'A' %>
      <%= form.label :customer_preference_A, 'A' %>
      <%= form.radio_button :customer_preference, 'B' %>
      <%= form.label :customer_preference_B, 'B' %>
      <%= form.radio_button :customer_preference, 'C' %>
      <%= form.label :customer_preference_C, 'C' %>
      <%= form.radio_button :customer_preference, '' %>
      <%= form.label :customer_preference_none, '不明' %>
    </div>
  </div>

  <div class= "mb-3" style="display: none">
    <%= form.label :store_id, style: "display: none", class: "form-label" %>
    <%= form.text_field :store_id, class: "form-control" %>
  </div>

  <div class="d-grid">
    <%= form.submit class: "btn btn-lg btn-primary"%>
  </div>
<% end %>

app/views/clerks/_form_modal.html.erb
<div class="card mb-3">
  <div class="card-body">
    <%= form_with(model: clerk, data: { action: "turbo:submit-end->form#handleSubmit" }) do |form| %>
      <% if clerk.errors.any? %>
        <div class="alert alert-danger alert-dismissible fade show">
          <strong><%= t('errors.template.header', 
                      count: clerk.errors.count, 
                      model: clerk.class.model_name.human) %>
          </strong>

          <ul class="m-0">
            <% clerk.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
          
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>

      <div class="row mb-3">
        <div class="col-6">
          <%= form.label :last_name, "姓氏", class: "form-label" %>
          <%= form.text_field :last_name, class: "form-control", placeholder: "请输入姓氏" %>
        </div>
        <div class="col-6">
          <%= form.label :first_name, "名字", class: "form-label" %>
          <%= form.text_field :first_name, class: "form-control", placeholder: "请输入名字" %>
        </div>
      </div>

      <div class="mb-3 d-flex align-items-center">
        <label class="form-label mb-0 me-3">性别</label>
        <div class="form-check form-check-inline">
          <%= form.radio_button :gender, '男', checked: true, class: "form-check-input" %>
          <%= form.label :gender_男, '男', class: "form-check-label" %>
        </div>
        <div class="form-check form-check-inline">
          <%= form.radio_button :gender, '女', class: "form-check-input" %>
          <%= form.label :gender_女, '女', class: "form-check-label" %>
        </div>
      </div>

      <div class="mb-3 d-flex align-items-center">
        <label class="form-label mb-0 me-3">客户倾向性</label>
        <div class="form-check form-check-inline" >
          <%= form.radio_button :customer_preference, 'A' %>
          <%= form.label :customer_preference_A, 'A' %>
        </div>
        <div class="form-check form-check-inline">
          <%= form.radio_button :customer_preference, 'B' %>
          <%= form.label :customer_preference_B, 'B' %>
        </div>
        <div class="form-check form-check-inline">
          <%= form.radio_button :customer_preference, 'C' %>
          <%= form.label :customer_preference_C, 'C' %>
        </div>
        <div class="form-check form-check-inline">
          <%= form.radio_button :customer_preference, '' %>
          <%= form.label :customer_preference_none, '未明' %>
        </div>
      </div>

      <div class="mb-3">
        <%= form.label :remark, "备注", class: "form-label" %>
        <%= form.text_area :remark, class: "form-control", rows: 3 %>
      </div>

      <%= form.hidden_field :store_id %>

      <div class="row">
        <div class="col-8">
          <%= form.submit "保存", class: "btn btn-primary w-100" %>
        </div>
        <div class="col-4">
          <button type="button" class="btn btn-outline-danger w-100" data-action="form#toggleForm">取消</button>
        </div>
      </div>
    <% end %>
  </div>
</div> 

app/views/clerks/edit.html.erb
<% content_for :title, "Editing clerk" %>

<h1>Editing clerk</h1>

<%= render "form", clerk: @clerk %>

<br>

<div>
  <%= link_to "Show this clerk", @clerk %> |
  <%= link_to "Back to clerks", clerks_path %>
</div>

app/views/clerks/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Clerks" %>

<h1>Clerks</h1>

<div id="clerks">
  <% @clerks.each do |clerk| %>
    <%= render clerk %>
    <p>
      <%= link_to "Show this clerk", clerk %>
    </p>
  <% end %>
</div>

<%= link_to "New clerk", new_clerk_path %>

app/views/clerks/new.html.erb
<% content_for :title, "New clerk" %>
<div class="row my-3">
  <span class="fs-5">新增店员到：
    <%= link_to @clerk.store.name, 
                store_path(@clerk.store), 
                class: "link-offset-2" %>
  </span>
</div>
<hr />
<%= render "form", clerk: @clerk %>

app/views/clerks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @clerk %>

<div>
  <%= link_to "Edit this clerk", edit_clerk_path(@clerk) %> |
  <%= link_to "Back to clerks", clerks_path %>

  <%= button_to "Destroy this clerk", @clerk, method: :delete %>
</div>