config/routes.rb
Rails.application.routes.draw do
  resources :stocks do
    resources :stock_change_logs, only: [ :index ]
  end
  resources :drugs
  resource :session
  resources :passwords, param: :token
  resources :clerks
  resources :stores do
    resources :visits
  end
  resources :inline_edits, only: [ :update ]
  get "dashboard/index"
  get "dashboard/store/:store_id", to: "dashboard#store", as: "dashboard/store/"
  post "dashboard/store/:store_id", to: "dashboard#store"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user
  has_many :clerks, dependent: :destroy
  has_many :stocks, dependent: :destroy
  has_many :drugs, through: :stocks
  has_many :visits, dependent: :destroy

  validates :name, :level, :address, presence: true
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: %i[ show edit update destroy ]

  # GET /stores or /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1 or /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores or /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: "Store was successfully created." }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1 or /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: "Store was successfully updated." }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1 or /stores/1.json
  def destroy
    @store.destroy!

    respond_to do |format|
      format.html { redirect_to stores_path, status: :see_other, notice: "Store was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def store_params
      params.expect(store: [ :name, :level, :description, :address ])
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store) do |form| %>
  <% if store.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show">
      <strong><%= t('errors.template.header', 
                    count: store.errors.count, 
                    model: store.class.model_name.human) %>
      </strong>

      <ul class="m-0">
        <% store.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>

      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, style: "display: block", class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :level, style: "display: block", class: "form-label" %>
    <%= form.text_field :level, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, style: "display: block", class: "form-label" %>
    <%= form.textarea :description, class: "form-control" %>
  </div>

  <div class="mb-4">
    <%= form.label :address, style: "display: block", class: "form-label" %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div class="d-grid">
    <%= form.submit class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/stores/_store.html.erb
<div class="card mb-2" id="<%= dom_id store %>">
  <div class="card-header">
    <% if local_assigns.has_key?(:index) %>
      <span class="badge rounded-pill text-bg-secondary"><%= index+1 %></span>
    <% end %>
    <span class="badge text-bg-primary pl-4 float-end">优先级：<%= store.level %></span>
  </div>
  <div class="card-body">
    <h5 class="card-title">
      <% if controller.controller_name == "dashboard" %>
        <%= link_to store.name, dashboard_store_path(store_id: store), class: "link-offset-2" %>
      <% else %>
        <%= link_to store.name, store, class: "link-offset-2" %>
      <% end %>
    </h5>
    <hr />
    <p class="card-text">
      地址：<%= store.address %>
    </p>
    <p class="card-text">
      简述：<%= store.description %>
    </p>
    <small class="card-text">
      数据更新于：<%= store.updated_at %>
    </small>
  </div>
</div>

app/views/stores/edit.html.erb
<% content_for :title, "Editing store" %>

<h1>Editing store</h1>

<%= render "form", store: @store %>

<br>

<div>
  <%= link_to "Show this store", @store %> |
  <%= link_to "Back to stores", stores_path %>
</div>

app/views/stores/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="row mt-2">
  <div class="col-6 mb-2">
    <h2>药房清单</h2>
  </div>
  <div class="col-6">
    <%= link_to "新建药店", new_store_path, class: "float-end link-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" %>
  </div>
  <div class="col-12" id="stores">
    <% @stores.each do |store| %>
      <%= render store %>
    <% end %>
  </div>
</div>

app/views/stores/new.html.erb
<% content_for :title, "New store" %>
<div class="row mt-2">
  <div class="col-6">
    <h2>新建药房</h2>
  </div>
  <div class="col-6"><%= link_to "返回清单", stores_path, class: "float-end link-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" %></div>
  <div class="col-12">
    <%= render "form", store: @store %>
  </div>
</div>

app/views/stores/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @store %>

<div class="mt-3 row">
  <div class="col-4"><%= link_to "修改药店", edit_store_path(@store), class: "btn btn-primary d-grid" %></div>
  <div class="col-4"><%= link_to "返回清单", stores_path, class: "btn btn-primary d-grid" %></div>
  <div class="col-4">
    <%= button_to "删除此店", 
                  @store, 
                  method: :delete,
                  data: { turbo_confirm: "确定删除此店吗？" },
                  form: { class: "d-grid" }, 
                  class: "btn btn-danger" %>
  </div>
</div>
<hr />
<div class="mt-3 row">
  <div class="col">
    <%= link_to "增加店员", new_clerk_path(store_id: @store), class: "btn btn-primary" %>
  </div>
</div>
<hr />
<% if @store.clerks %>

  <% @store.clerks.each do |clerk| %>
    <%= render clerk %>
  <% end %>

<% end %>